### ISSUE TITLE
save creation error: global key read

### ISSUE THREAD

**Issue by anonhostpi** [anonhostpi/mk-fg-games#1]
![image](https://github.com/user-attachments/assets/10000b4e-fb87-4357-aed2-82d02616ebdc)

> ```
> The mod Moon Logic (0.0.83) caused a non-recoverable error.
> Please report this error to the mod author.
> 
> Error while running event Moon_Logic::on_init()
> __Moon_Logic__/control.lua:934: 
> 
> [ENV Error] Forbidden global *read*:
> {key = "global"}
> 
> stack traceback:
> 	[C]: in function 'error'
> 	__Moon_Logic__/control.lua:928: in function '__index'
> 	__Moon_Logic__/control.lua:934: in function 'update_signal_types_table'
> 	__Moon_Logic__/control.lua:959: in function <__Moon_Logic__/control.lua:957>
> ```

**Comment by anonhostpi** [comment]
problem causer:

https://github.com/anonhostpi/mk-fg-games/blob/8ba62b40a7026481ed47ff4eb8e885715474129a/factorio/Moon_Logic/control.lua#L917-L948

I'm not entirely sure how this was meant to work initially, because strict mode is enabled before global is accessed.

https://github.com/anonhostpi/mk-fg-games/blob/8ba62b40a7026481ed47ff4eb8e885715474129a/factorio/Moon_Logic/control.lua#L957-L961

maybe game has been renamed to global?

**Comment by anonhostpi** [comment]
global has been renamed to storage and storage is not a key on _ENV

https://github.com/mk-fg/games/pull/9#issuecomment-2429703084

**Comment by mk-fg** [comment]
Yeah, that "strict mode" hack is there exactly to catch this kind of issues, as default lua behavior is to return nil for any undefined var (or worse - set it globally), which often ends up being undetected until some rare hard-to-reproduce bug pops-up because of it.
